#  /etc/syslog.conf	Configuration file for busybox's syslogd utility
local2.* /var/log/oran-trace.log
local3.* /var/log/oran-troubleshooting.log

# example for sending some logs to remote log server
# need setup on the server side as well
# authpriv.* @rtpalab3-u04.ad.analog.com
