OS_RELEASE_FIELDS:append = " MACHINE HOME_URL SUPPORT_URL BUG_REPORT_URL"
HOME_URL = "https://github.com/analogdevicesinc"
SUPPORT_URL = "https://github.com/analogdevicesinc"
BUG_REPORT_URL = "https://github.com/analogdevicesinc"
VERSION_ID = "${VERSION_META}"
