SUMMARY = "Installs the factory reset swu into the target rootfs"
DESCRIPTION = "Copies the .swu generated by adrv906x-factory-reset-swu-image into target rootfs"
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://${COMMON_LICENSE_DIR}/MIT;md5=0835ade698e0bcf8506ecda2f7b4f302"

# Ensure the .swu exists before we run do_install:
do_install[depends] += "adrv906x-factory-reset-swu-image:do_swuimage"

# Match the image name from the swu-factory-reset recipe
IMAGE_NAME = "factory-reset"

# Rootfs path for storing the SWU
INSTALL_DIR = "${datadir}"

S = "${WORKDIR}"

do_install() {
    install -d ${D}${INSTALL_DIR}

    # The .swu is deployed by swu-factory-reset into ${DEPLOY_DIR_IMAGE}
    src="${DEPLOY_DIR_IMAGE}/${IMAGE_NAME}.swu"
    dst="${D}${INSTALL_DIR}/${IMAGE_NAME}.swu"

    if [ -f "${src}" ]; then
        install -m 0644 "${src}" "${dst}"
    else
        bbfatal "Factory reset SWU not found: ${src}"
    fi
}

FILES:${PN}:append = " ${INSTALL_DIR}/${IMAGE_NAME}.swu"
