#! /bin/sh
set -e

PIDFILE=/var/run/.pid

# source function library
. /etc/init.d/functions

case "$1" in
  start)
        # channel 12 - Titan
        echo 1 > /sys/bus/iio/devices/iio\:device0/out_voltage12_en
        echo 1000000 >  /sys/bus/iio/devices/iio\:device0/out_voltage12_raw

        # channel 13 - Denali
        echo 1 > /sys/bus/iio/devices/iio\:device0/out_voltage13_en
        echo 1000000 >  /sys/bus/iio/devices/iio\:device0/out_voltage13_raw
        ;;
  stop)
        ;;
  *)
        echo "Usage: /etc/init.d/reduce-fan-speed {start|stop}"
        exit 1
esac
exit 0
