#!/bin/sh

EXT4_GUID="0FC63DAF-8483-4772-8E79-3D69D8477DE4"

ROOT="/mnt/.root"
METADATA="/mnt/.meta"
MAPPER_NAME=rootfs

echo "Starting /init on initramfs..."

# Pet watchdog
echo '\0' > /dev/watchdog

# mount temporary filesystems
mount -n -t devtmpfs devtmpfs /dev
mount -n -t proc     proc     /proc
mount -n -t sysfs    sysfs    /sys
mount -n -t tmpfs    tmpfs    /run

# use the /dev/console device node from devtmpfs if possible to not
# confuse glibc's ttyname_r().
# This may fail (E.G. booted with console=), and errors from exec will
# terminate the shell, so use a subshell for the test
if (exec 0</dev/console) 2>/dev/null; then
    exec 0</dev/console
    exec 1>/dev/console
    exec 2>/dev/console
fi

# Secondary boot stops at initramfs
if [ -f /proc/device-tree/chosen/boot/secondary-tile ]
then
    # Setup tmpfs on /tmp
    mkdir /var/volatile
    mount -t tmpfs tmpfs /var/volatile
    mkdir /var/volatile/tmp
    chmod a+rwxt /var/volatile/tmp
    ln -s /var/volatile/tmp /tmp

    # Setup devpts (for ssh)
    mkdir -p /dev/pts
    mount -t devpts devpts /dev/pts

    # Setup a home dir for root (for ssh)
    mkdir -p /home/root

    # Start jitterentropy service
    /etc/init.d/jitterentropy start

    # Start ssh server
    /etc/init.d/dropbear start

    # Let the primary know that boot is complete
    stdbuf -o0 echo "Secondary tile is active. Halting boot."

    # Stop using this tty as a console
    dmesg -n1
    exec 0</dev/null
    exec 1>/dev/null
    exec 2>/dev/null

    PPP_TTY=/dev/ttyAMA0
    # TODO: SystemC uses physical UART due to vUART latency issues
    # Remove this if/when SystemC support is removed
    PLAT=$(cat /proc/device-tree/chosen/boot/plat)
    if [ "${PLAT}" = "sysc" ]
    then
        PPP_TTY=/dev/ttyAMA4
    fi

    # Bring up PPP on this tty
    mkdir /var/run
    pppd $PPP_TTY lock noipv6 4000000 local silent xonxoff noauth nodetach &

    while true
    do
        sleep 1
    done
fi;

# If the NFS config file is present and NFS boot is enabled,
# mount the rootfs via NFS and the data partition from a tmpfs
if [ -f /etc/nfs-cfg.env ]
then
    source /etc/nfs-cfg.env
    if [ "${NFS_ENABLED}" -eq 1 ]
    then
        NFS_MOUNT_OPTS=vers=3,rsize=4096,wsize=4096,namlen=255,hard,nolock,proto=tcp,timeo=600,retrans=2,sec=sys,mountvers=3,mountproto=tcp,local_lock=all
        ifconfig "$NFS_INTF" "$NFS_LCL_IP_ADDR"
        /etc/init.d/rpcbind start
        /etc/init.d/nfscommon start
        NFS_ROOT_PART="${NFS_HOST_IP_ADDR}:${NFS_SHARE_PATH}"
        echo "Mounting rootfs on ${NFS_ROOT_PART}..."
        [ -d ${ROOT} ] || mkdir -p ${ROOT}
        mount -t nfs -o ro -o "${NFS_MOUNT_OPTS}" "${NFS_ROOT_PART}" "${ROOT}"
        echo "Mounting data partition on tmpfs..."
        mount -n -t tmpfs tmpfs "${ROOT}/data/active"
        echo "Switching to rootfs..."
        cd ${ROOT} || exit 1
        exec switch_root . "/init" "$@"
    fi
fi

# Get the active boot device and boot slot from the device tree 'chosen' node
BOOT_DEV_ID=$(cat /proc/device-tree/chosen/boot/device)
BOOT_SLOT=$(cat /proc/device-tree/chosen/boot/slot)
BOOT_PLAT=$(tr -d '\0' < /proc/device-tree/chosen/boot/plat)
echo "Active boot device: ${BOOT_DEV_ID}"
echo "Active boot slot: ${BOOT_SLOT}"

# Setup the boot device and rootfs device
if [ "${BOOT_DEV_ID}" = "emmc0" ]; then
    BOOT_DEV="/dev/mmcblk0"
    ROOTFS_DEV=$BOOT_DEV
elif [ "${BOOT_DEV_ID}" = "sd0" ]; then
    BOOT_DEV="/dev/mmcblk1"
    ROOTFS_DEV=$BOOT_DEV
elif [ "${BOOT_DEV_ID}" = "qspi0" ]; then
    BOOT_DEV="/dev/mtdblock"
    ROOTFS_DEV="/dev/mmcblk0"
else
    echo "Invalid boot device ${BOOT_DEV_ID}"
    exit 1
fi;

# Workaround: Prevent ./init from accessing partitions before being ready.
#             Otherwise, the access fails and the kernel resets the system.
#             eMMC HSx00 modes configuration sometimes completes after this point.
if [ "${BOOT_DEV_ID}" = "emmc0" ]; then
    counter=0
    while true
    do
        if [ -n "$(grep mmcblk0 /proc/partitions)" ]; then break; fi;

        # Wait up to 1s
        counter=$((counter+1))
        if [ "$counter" -eq "10" ]; then echo "Error: eMMC partitions are not ready"; break; fi
        sleep 0.1
    done
fi;

# Find the rootfs partition by name
ROOTFS_PART_NAME=rootfs_${BOOT_SLOT}
ROOTFS_PART_NUM=$(gdisk -l $ROOTFS_DEV | grep " ${ROOTFS_PART_NAME}" | tr -s " " " " | cut -d' ' -f2)
ROOTFS_PART=${ROOTFS_DEV}p${ROOTFS_PART_NUM}

# Find and source the rootfs configuration file
if [ ! -f /etc/rootfs-cfg.env ]
then
    echo "/etc/rootfs-cfg.env is missing"
    echo 1 > /sys/kernel/err/reset_cause
    reboot -f now
fi
source /etc/rootfs-cfg.env

# Setup dm-verity-related parameters
HASH_OFFSET=$DATA_SIZE
FEC_OFFSET=0
[ "$FEC_ENABLED" -ne 0 ] && FEC_OFFSET=$((HASH_OFFSET+HASH_SIZE))

if [ "$DM_VERITY_ENABLED" -eq 0 ]
then
    echo "WARN: SECURE BOOT IS DISABLED. dm-verity is OFF for ${ROOTFS_PART}."
else
    echo "Setting up dm-verity for ${ROOTFS_PART}..."
    VERITY_OPTS="--verbose --hash-offset=$HASH_OFFSET"
    [ "$FEC_ENABLED" -ne 0 ] && VERITY_OPTS="$VERITY_OPTS --fec-device=$ROOTFS_PART --fec-offset=$FEC_OFFSET --fec-roots=$FEC_ROOTS"
    VERITY_OPTS="$VERITY_OPTS --panic-on-corruption"
    /usr/sbin/veritysetup open \
        "${ROOTFS_PART}" $MAPPER_NAME "${ROOTFS_PART}" "$ROOT_HASH" $VERITY_OPTS
    ROOTFS_PART=/dev/mapper/$MAPPER_NAME
fi

DATA_PART_NUM=$(gdisk -l $ROOTFS_DEV | grep " data$" | tr -s " " " " | cut -d' ' -f2)
DATA_PART="${ROOTFS_DEV}p${DATA_PART_NUM}"
if [ -n "$DATA_PART_NUM" ]
then
    DATA_PART_TYPE=$(sgdisk -i "$DATA_PART_NUM" "$ROOTFS_DEV" | grep "Partition GUID code" | cut -d ':' -f2 | cut -d ' ' -f2)

    if [ "$DATA_PART_TYPE" != "$EXT4_GUID" ]
    then
        if [ "$BOOT_PLAT" == "asic" ]
        then
            echo "Expanding data partition to fill disk..."
            sgdisk -e \
                    -d "$DATA_PART_NUM" \
                    -n "$DATA_PART_NUM:0:0" \
                    -c "$DATA_PART_NUM:data" \
                "$ROOTFS_DEV"
        fi
        echo "Creating EXT4 filesystem on data partition..."
        mkfs.ext4 -F -L data "$DATA_PART"
        sgdisk -t "$DATA_PART_NUM:$EXT4_GUID" "$ROOTFS_DEV"
    fi
fi

echo "Mounting rootfs on ${ROOTFS_PART}..."
[ -d ${ROOT} ] || mkdir -p ${ROOT}
mount ${ROOTFS_PART} ${ROOT}

# Mount the data partition
if [ -n "$DATA_PART_NUM" ]
then
    echo "Mounting data partition on ${DATA_PART}..."
    mount -o noexec,nosuid,nodev "${DATA_PART}" "${ROOT}/data/active"
else
    echo "Unable to find data partition on ${ROOTFS_DEV}. Skipping mount."
fi

if [ -f "${ROOT}/etc/anti-rollback-version" ]
then
    # Read anti-rollback counter stored in rootfs
    anti_rollback_counter=$(cat "${ROOT}/etc/anti-rollback-version")

    # Verify enforcement-counter node exists in kernel device tree
    if [ ! -f "/proc/device-tree/chosen/boot/anti-rollback/enforcement-counter" ]
    then
        echo "Unable to find enforcement-counter node in kernel device tree"
        echo 1 > "/sys/kernel/err/reset_cause"
        reboot -f now
    fi

    # Read enforcement counter stored in device tree by U-Boot
    enforcement_counter=$(cat "/proc/device-tree/chosen/boot/anti-rollback/enforcement-counter")

    # If anti-rollback counter is less than enforcement counter, set reset cause and trigger warm reset
    if [ "$anti_rollback_counter" -lt "$enforcement_counter" ]
    then
        echo "Rootfs failed anti-rollback enforcement check"
        echo 1 > "/sys/kernel/err/reset_cause"
        reboot -f now
    fi
else
    # Reset if anti-rollback counter is not found in rootfs
    echo "Unable to find anti-rollback counter in rootfs"
    echo 1 > "/sys/kernel/err/reset_cause"
    reboot -f now
fi

echo "Switching to rootfs..."
cd ${ROOT} || exit 1
exec switch_root . "/init" "$@"
