# Remove previously defined rules
flush ruleset

# Filter table for IPv4/IPv6 (inet)
table inet filter {

    chain inbound {
        # Accept all
        type filter hook input priority 0; policy accept;

        # EXAMPLES:
        #
        # # Drop all
        # type filter hook input priority 0; policy drop;
        #
        # # Accept IPv4 ICMP ping
        # icmp type echo-request accept
        #
        # # Accept IPv4 ICMP ping, limited to 5 per second
        # icmp type echo-request limit rate 5/second accept
        #
        # # Accept loopback
        # iifname lo accept
        #
        # # Accept SSH (TCP/22), HTTP (TCP/80) and HTTPS (TCP/443)
        # tcp dport {ssh, http, https} accept
        #
        # # Accept eCPRI (https://wiki.wireshark.org/eCPRI)
        # meta protocol 0xAEFE accept
        #
        # # Accept PTP (https://wiki.wireshark.org/Protocols/ptp)
        # udp dport {319, 320} accept
        #
        # # Accept ESMC
        # meta protocol 0x8809 accept
        #
        # # Accept NETCONF over SSH
        # tcp dport 830 accept
        #
        # # Accept NETCONF over TSL
        # tcp dport 6513 accept
        #
        # # Accept EAPOL
        # meta protocol 0x888E accept
    }

    chain forward {
        # Accept all
        type filter hook forward priority 0; policy accept;
    }

    chain outbound {
        # Accept all
        type filter hook output priority 0; policy accept;
    }
}