# Remove previously defined rules
flush ruleset

# Filter table for IPv4/IPv6 (inet)
table inet filter {

    chain inbound {
        # Drop all
        type filter hook input priority 0; policy drop;

        # allow icmp
        ip protocol icmp accept

        # Accept SSH (TCP/22), HTTP (TCP/80) and HTTPS (TCP/443)
        tcp dport {ssh, http, https} accept

        # Accept PTP (https://wiki.wireshark.org/Protocols/ptp)
        udp dport {319, 320} accept

        # Accept NETCONF over SSH
        tcp dport 830 accept

        # Accept NETCONF over TLS
        tcp dport 6513 accept

        # serdes status port on loopback interface
        iifname lo tcp dport 18081 accept

        # mosquitto, need to allow QA team to access remotely
        tcp dport 1883 accept

        # EAPOL
        meta protocol 0x888E accept

        # ESMC for syncE
        meta protocol 0x8809 accept

        # eCPRI 
        meta protocol 0xAEFE accept
    }

    chain forward {
        # Drop all
        type filter hook forward priority 0; policy drop;
    }

    chain outbound {
        # Accept all
        type filter hook output priority 0; policy accept;
    }
}
